import { Nav } from "@/components/Nav";
import { BrandPageHeader } from "@/components/BrandPageHeader";
import { BrandStoryVisual } from "@/components/BrandStoryVisual";
import { getStats, getPools } from "@/lib/data";
import { compact } from "@/lib/format";
import { Coins, ArrowsClockwise, RocketLaunch, ShareNetwork, TrendUp, Wallet, ArrowRight } from "@phosphor-icons/react/dist/ssr";

export default async function RewardsPage() {
  const [stats, pools] = await Promise.all([getStats(), getPools()]);
  const poolFees24h = pools.reduce((s, p) => s + p.fees24hUsd, 0);

  return (
    <main className="min-h-[100dvh] bg-bg">
      <Nav />
      <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
        <BrandPageHeader
          eyebrow="Holder rewards"
          title="Fees flow back into the bubble."
          description="Launch, migrate into multiple stock pools, compound fees, and grow holder reflections over time."
        >
          <BrandStoryVisual variant="rewards" />
        </BrandPageHeader>

        {/* top stats */}
        <div className="relative z-10 -mt-4 grid gap-4 px-3 sm:grid-cols-3 sm:px-6">
          <Tile icon={<Coins size={22} weight="fill" />} value={compact(stats.feesDistributedUsd)} label="Reflections generated" />
          <Tile icon={<ArrowsClockwise size={22} weight="fill" />} value={compact(poolFees24h)} label="24h fees compounding" />
          <Tile icon={<ShareNetwork size={22} weight="fill" />} value={String(pools.length)} label="Live compounding pools" />
        </div>

        <div className="home-flow-grid mt-6 grid gap-4 md:grid-cols-4">
          {[
            { icon: <RocketLaunch size={21} weight="fill" />, title: "Launch", copy: "Launch a BubbleStock through the Dynamic Bonding Curve." },
            { icon: <ShareNetwork size={21} weight="fill" />, title: "Multipool migration", copy: "Route liquidity into several STOCK/USDC pools when the BubbleStock migrates." },
            { icon: <ArrowsClockwise size={21} weight="fill" />, title: "Compound fees", copy: "BubbleStock trading fees seed and deepen those STOCK/USDC pools." },
            { icon: <TrendUp size={21} weight="fill" />, title: "Grow reflections", copy: "Deeper pools generate reflections for holders over time." },
          ].map((step, index) => (
            <article key={step.title} className="home-flow-step card rounded-2xl p-5">
              <div className="flex items-center justify-between">
                <span className="grid h-10 w-10 place-items-center rounded-xl bg-brand/10 text-brand">{step.icon}</span>
                <span className="tnum text-xs font-bold text-ink-faint">0{index + 1}</span>
              </div>
              <h2 className="mt-4 font-display text-lg font-bold text-ink">{step.title}</h2>
              <p className="mt-2 text-sm leading-relaxed text-ink-soft">{step.copy}</p>
            </article>
          ))}
        </div>

        <div className="mt-6 card flex items-start gap-4 rounded-2xl p-6">
          <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-up/10 text-up"><TrendUp size={22} weight="fill" /></span>
          <div>
            <h2 className="font-display text-lg font-bold text-ink">Reflections grow with liquidity</h2>
            <p className="mt-1 text-sm leading-relaxed text-ink-soft">The mechanism is cumulative: launches bootstrap stock liquidity, fees compound into the selected pools, and growing pool activity increases holder reflections over time.</p>
          </div>
        </div>

        {/* your rewards */}
        <div className="mt-6 card flex flex-col items-start gap-4 rounded-2xl p-6 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <span className="grid h-11 w-11 place-items-center rounded-xl bg-brand/10 text-brand"><Wallet size={22} weight="fill" /></span>
            <div>
              <div className="font-display font-bold text-ink">Your rewards</div>
              <div className="text-sm text-ink-soft">Connect a wallet to see the reflections generated by your BubbleStocks.</div>
            </div>
          </div>
          <span className="inline-flex items-center gap-1 rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white">
            Connect wallet <ArrowRight size={14} weight="bold" />
          </span>
        </div>
      </div>
    </main>
  );
}

function Tile({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) {
  return (
    <div className="card rounded-2xl p-5">
      <span className="grid h-9 w-9 place-items-center rounded-lg bg-brand/10 text-brand">{icon}</span>
      <div className="tnum mt-3 font-display text-2xl font-bold text-ink">{value}</div>
      <div className="mt-0.5 text-sm text-ink-soft">{label}</div>
    </div>
  );
}
